# Generated by Django 3.0.5 on 2020-04-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('row_id', models.IntegerField(db_column='ROW_ID', primary_key=True, serialize=False)),
                ('hadm_id', models.IntegerField(blank=True, db_column='HADM_ID', null=True, unique=True)),
                ('admittime', models.CharField(blank=True, db_column='ADMITTIME', max_length=50, null=True)),
                ('dischtime', models.CharField(blank=True, db_column='DISCHTIME', max_length=50, null=True)),
                ('deathtime', models.CharField(blank=True, db_column='DEATHTIME', max_length=50, null=True)),
                ('admission_type', models.CharField(blank=True, db_column='ADMISSION_TYPE', max_length=50, null=True)),
                ('admission_location', models.CharField(blank=True, db_column='ADMISSION_LOCATION', max_length=50, null=True)),
                ('discharge_location', models.CharField(blank=True, db_column='DISCHARGE_LOCATION', max_length=50, null=True)),
                ('insurance', models.CharField(blank=True, db_column='INSURANCE', max_length=255, null=True)),
                ('language', models.CharField(blank=True, db_column='LANGUAGE', max_length=10, null=True)),
                ('religion', models.CharField(blank=True, db_column='RELIGION', max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, db_column='MARITAL_STATUS', max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, db_column='ETHNICITY', max_length=200, null=True)),
                ('edregtime', models.CharField(blank=True, db_column='EDREGTIME', max_length=50, null=True)),
                ('edouttime', models.CharField(blank=True, db_column='EDOUTTIME', max_length=50, null=True)),
                ('diagnosis', models.CharField(blank=True, db_column='DIAGNOSIS', max_length=300, null=True)),
                ('hospital_expire_flag', models.IntegerField(blank=True, db_column='HOSPITAL_EXPIRE_FLAG', null=True)),
                ('has_chartevents_data', models.IntegerField(blank=True, db_column='HAS_CHARTEVENTS_DATA', null=True)),
            ],
            options={
                'db_table': 'admissions',
            },
        ),
        migrations.CreateModel(
            name='Caregivers',
            fields=[
                ('row_id', models.IntegerField(db_column='ROW_ID', primary_key=True, serialize=False)),
                ('cgid', models.IntegerField(blank=True, db_column='CGID', null=True, unique=True)),
                ('label', models.CharField(blank=True, db_column='LABEL', max_length=15, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=30, null=True)),
            ],
            options={
                'db_table': 'caregivers',
            },
        ),
        migrations.CreateModel(
            name='DCpt',
            fields=[
                ('row_id', models.IntegerField(db_column='ROW_ID', primary_key=True, serialize=False)),
                ('category', models.SmallIntegerField(blank=True, db_column='CATEGORY', null=True)),
                ('sectionrange', models.CharField(blank=True, db_column='SECTIONRANGE', max_length=100, null=True)),
                ('sectionheader', models.CharField(blank=True, db_column='SECTIONHEADER', max_length=50, null=True)),
                ('subsectionrange', models.CharField(blank=True, db_column='SUBSECTIONRANGE', max_length=100, null=True, unique=True)),
                ('subsectionheader', models.CharField(blank=True, db_column='SUBSECTIONHEADER', max_length=300, null=True)),
                ('codesuffix', models.CharField(blank=True, db_column='CODESUFFIX', max_length=5, null=True)),
                ('mincodeinsubsection', models.IntegerField(blank=True, db_column='MINCODEINSUBSECTION', null=True)),
                ('maxcodeinsubsection', models.IntegerField(blank=True, db_column='MAXCODEINSUBSECTION', null=True)),
            ],
            options={
                'db_table': 'd_cpt',
            },
        ),
        migrations.CreateModel(
            name='DLabitems',
            fields=[
                ('row_id', models.IntegerField(db_column='ROW_ID', primary_key=True, serialize=False)),
                ('itemid', models.IntegerField(blank=True, db_column='ITEMID', null=True, unique=True)),
                ('label', models.CharField(blank=True, db_column='LABEL', max_length=100, null=True)),
                ('fluid', models.CharField(blank=True, db_column='FLUID', max_length=100, null=True)),
                ('category', models.CharField(blank=True, db_column='CATEGORY', max_length=100, null=True)),
                ('loinc_code', models.CharField(blank=True, db_column='LOINC_CODE', max_length=100, null=True)),
            ],
            options={
                'db_table': 'd_labitems',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('row_id', models.IntegerField(db_column='ROW_ID', primary_key=True, serialize=False)),
                ('subject_id', models.IntegerField(blank=True, db_column='SUBJECT_ID', null=True, unique=True)),
                ('gender', models.CharField(blank=True, db_column='GENDER', max_length=5, null=True)),
                ('dob', models.CharField(blank=True, db_column='DOB', max_length=50, null=True)),
                ('dod', models.CharField(blank=True, db_column='DOD', max_length=50, null=True)),
                ('dod_hosp', models.CharField(blank=True, db_column='DOD_HOSP', max_length=50, null=True)),
                ('dod_ssn', models.CharField(blank=True, db_column='DOD_SSN', max_length=50, null=True)),
                ('expire_flag', models.CharField(blank=True, db_column='EXPIRE_FLAG', max_length=5, null=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('row_id', models.IntegerField(db_column='ROW_ID', primary_key=True, serialize=False)),
                ('icustay_id', models.IntegerField(blank=True, db_column='ICUSTAY_ID', null=True)),
                ('startdate', models.CharField(blank=True, db_column='STARTDATE', max_length=50, null=True)),
                ('enddate', models.CharField(blank=True, db_column='ENDDATE', max_length=50, null=True)),
                ('drug_type', models.CharField(blank=True, db_column='DRUG_TYPE', max_length=100, null=True)),
                ('drug', models.CharField(blank=True, db_column='DRUG', max_length=100, null=True)),
                ('drug_name_poe', models.CharField(blank=True, db_column='DRUG_NAME_POE', max_length=100, null=True)),
                ('drug_name_generic', models.CharField(blank=True, db_column='DRUG_NAME_GENERIC', max_length=100, null=True)),
                ('formulary_drug_cd', models.CharField(blank=True, db_column='FORMULARY_DRUG_CD', max_length=120, null=True)),
                ('gsn', models.CharField(blank=True, db_column='GSN', max_length=200, null=True)),
                ('ndc', models.CharField(blank=True, db_column='NDC', max_length=120, null=True)),
                ('prod_strength', models.CharField(blank=True, db_column='PROD_STRENGTH', max_length=120, null=True)),
                ('dose_val_rx', models.CharField(blank=True, db_column='DOSE_VAL_RX', max_length=120, null=True)),
                ('dose_unit_rx', models.CharField(blank=True, db_column='DOSE_UNIT_RX', max_length=120, null=True)),
                ('form_val_disp', models.CharField(blank=True, db_column='FORM_VAL_DISP', max_length=120, null=True)),
                ('form_unit_disp', models.CharField(blank=True, db_column='FORM_UNIT_DISP', max_length=120, null=True)),
                ('route', models.CharField(blank=True, db_column='ROUTE', max_length=120, null=True)),
                ('hadm', models.ForeignKey(blank=True, db_column='HADM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.Admissions')),
                ('subject', models.ForeignKey(blank=True, db_column='SUBJECT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.Patients')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='Labevents',
            fields=[
                ('row_id', models.IntegerField(db_column='ROW_ID', primary_key=True, serialize=False)),
                ('itemid', models.IntegerField(blank=True, db_column='ITEMID', null=True)),
                ('charttime', models.CharField(blank=True, db_column='CHARTTIME', max_length=50, null=True)),
                ('value', models.CharField(blank=True, db_column='VALUE', max_length=200, null=True)),
                ('valuenum', models.FloatField(blank=True, db_column='VALUENUM', null=True)),
                ('valueuom', models.CharField(blank=True, db_column='VALUEUOM', max_length=20, null=True)),
                ('flag', models.CharField(blank=True, db_column='FLAG', max_length=20, null=True)),
                ('hadm', models.ForeignKey(blank=True, db_column='HADM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.Admissions')),
                ('subject', models.ForeignKey(blank=True, db_column='SUBJECT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.Patients')),
            ],
            options={
                'db_table': 'labevents',
            },
        ),
        migrations.CreateModel(
            name='Datetimeevents',
            fields=[
                ('row_id', models.IntegerField(db_column='ROW_ID', primary_key=True, serialize=False)),
                ('icustay_id', models.IntegerField(blank=True, db_column='ICUSTAY_ID', null=True)),
                ('itemid', models.IntegerField(blank=True, db_column='ITEMID', null=True)),
                ('charttime', models.CharField(blank=True, db_column='CHARTTIME', max_length=50, null=True)),
                ('storetime', models.CharField(blank=True, db_column='STORETIME', max_length=50, null=True)),
                ('value', models.CharField(blank=True, db_column='VALUE', max_length=50, null=True)),
                ('valueuom', models.CharField(blank=True, db_column='VALUEUOM', max_length=50, null=True)),
                ('warning', models.SmallIntegerField(blank=True, db_column='WARNING', null=True)),
                ('error', models.SmallIntegerField(blank=True, db_column='ERROR', null=True)),
                ('resultstatus', models.CharField(blank=True, db_column='RESULTSTATUS', max_length=50, null=True)),
                ('stopped', models.CharField(blank=True, db_column='STOPPED', max_length=50, null=True)),
                ('cgid', models.ForeignKey(blank=True, db_column='CGID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.Caregivers')),
                ('hadm', models.ForeignKey(blank=True, db_column='HADM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.Admissions')),
                ('subject', models.ForeignKey(blank=True, db_column='SUBJECT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.Patients')),
            ],
            options={
                'db_table': 'datetimeevents',
            },
        ),
        migrations.CreateModel(
            name='Cptevents',
            fields=[
                ('row_id', models.IntegerField(db_column='ROW_ID', primary_key=True, serialize=False)),
                ('costcenter', models.CharField(blank=True, db_column='COSTCENTER', max_length=10, null=True)),
                ('chartdate', models.CharField(blank=True, db_column='CHARTDATE', max_length=50, null=True)),
                ('cpt_cd', models.CharField(blank=True, db_column='CPT_CD', max_length=10, null=True)),
                ('cpt_number', models.IntegerField(blank=True, db_column='CPT_NUMBER', null=True)),
                ('cpt_suffix', models.CharField(blank=True, db_column='CPT_SUFFIX', max_length=5, null=True)),
                ('ticket_id_seq', models.IntegerField(blank=True, db_column='TICKET_ID_SEQ', null=True)),
                ('sectionheader', models.CharField(blank=True, db_column='SECTIONHEADER', max_length=50, null=True)),
                ('subsectionheader', models.CharField(blank=True, db_column='SUBSECTIONHEADER', max_length=300, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=200, null=True)),
                ('hadm', models.ForeignKey(blank=True, db_column='HADM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.Admissions')),
                ('subject', models.ForeignKey(blank=True, db_column='SUBJECT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.Patients')),
            ],
            options={
                'db_table': 'cptevents',
            },
        ),
        migrations.AddField(
            model_name='admissions',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='SUBJECT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hospital.Patients'),
        ),
    ]
