# Generated by Django 3.0.5 on 2020-04-13 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20200413_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='caregivers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cptevents',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='datetimeevents',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dcpt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dlabitems',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='labevents',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prescriptions',
            options={'managed': False},
        ),
    ]
