# Generated by Django 3.0.5 on 2020-05-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20200413_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissions',
            options={'managed': False, 'verbose_name': '问诊', 'verbose_name_plural': '问诊'},
        ),
        migrations.AlterModelOptions(
            name='caregivers',
            options={'managed': False, 'verbose_name': '医护人员', 'verbose_name_plural': '医护人员'},
        ),
        migrations.AlterModelOptions(
            name='labevents',
            options={'managed': False, 'verbose_name': '检查', 'verbose_name_plural': '检查'},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'managed': False, 'verbose_name': '病人', 'verbose_name_plural': '病人'},
        ),
        migrations.AlterModelOptions(
            name='prescriptions',
            options={'managed': False, 'verbose_name': '处方', 'verbose_name_plural': '处方'},
        ),
    ]
