# Generated by Django 3.0.5 on 2020-05-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmstring',
            options={'ordering': ['-c_time'], 'verbose_name': '验证码', 'verbose_name_plural': '验证码'},
        ),
    ]
