# Generated by Django 3.0.5 on 2020-05-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200513_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '找回账户验证码',
                'verbose_name_plural': '找回账户验证码',
                'ordering': ['-c_time'],
            },
        ),
    ]
