# Generated by Django 3.0.5 on 2020-05-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_resetconfirmstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
